### ISSUE TITLE
install apk报文件报文件找不到

### ISSUE THREAD

**Issue by leizhiyuan** [maoruibin/TranslateApp#10]
本地编译部署会报找不到apk,应该是时区的问题,
![utc_settings](https://cloud.githubusercontent.com/assets/2684384/14035085/fcabd8cc-f264-11e5-8c54-04ae6af688c0.jpg)
截图如上,系统时间0325,打包安装会找0324的,相同问题在这里.
[emptythrowable-the-apk-file-apk-does-not-exist-on-disk](http://stackoverflow.com/questions/35545579/emptythrowable-the-apk-file-apk-does-not-exist-on-disk)

修改app.gradle解决. 获取中国时区.
```
//格式化打完完成后APK名称中的时间
def releaseTime() {
    return new Date().format("yyyy-MM-dd", TimeZone.getTimeZone("UTC+8"))
}
```

**Comment by maoruibin** [comment]
我最近也看到了这个问题，但是我没有细究，不错，我试试！

**Comment by maoruibin** [comment]
我已经把代码更新了~
