### ISSUE TITLE
在红米手机上不能使用

### ISSUE THREAD

**Issue by Veeson** [maoruibin/TranslateApp#17]
不知道是不是我的操作方法不对还是其它原因，我选中文字点击复制按钮后并没有显示翻译提示。

**Comment by maoruibin** [comment]
你复制的是英文吗？

**Comment by Veeson** [comment]
不好意思，现在才看到回复，复制中文和英文都不可以。

2016-06-03 22:10 GMT+08:00 咕咚 <notifications@github.com>:

**Comment by maoruibin** [comment]
你可能需要为 咕咚翻译 开启显示悬浮窗的权限

**Comment by TellH** [comment]
@maoruibin 我的米3需要按一下home键回到桌面后才会显示悬浮窗，在应用中不会显示。Android手机的适配真是麻烦啊。。。
