### ISSUE TITLE
在本应用外收藏成功单词后，没有成功提示 这个复现的case有么?

### ISSUE THREAD

**Issue by leizhiyuan** [maoruibin/TranslateApp#2]
自己尝试了在pocket,medium.chrome中选词,顶部弹出翻译结果后,点击收藏.底部都可以弹出"收藏成功"

请问这个问题是怎么复现的?

**Comment by maoruibin** [comment]
我在自己手机上 不论是6.0的小米4 还是 4.4的红米note 这个提示语始终系那是不出来。你用的什么手机？

**Comment by leizhiyuan** [comment]
我是魅族mx4，系统是cm12，android 5.1

咕咚 <notifications@github.com>于2016年3月5日周六 下午12:17写道：
