### ISSUE TITLE
计时

### ISSUE THREAD

**Issue by cnmao** [maoruibin/TranslateApp#6]
用户在一个时间限制下最后时刻第二次取词，会关闭翻译。

**Comment by leizhiyuan** [comment]
你说的意思是说:

1.用户设置了显示时间,比如4s
2.然后再次取另一词翻译,上一个翻译结果的弹窗会关闭对吗?

**Comment by cnmao** [comment]
恩  我点的时候出现了这个问题 。你们确认一下 。东西是好的，昨天我用的时候感觉非常好。感谢

**Comment by maoruibin** [comment]
>用户在一个时间限制下最后时刻第二次取词，会关闭翻译。

目前确实是这样，没什么问题，第二次取词就是应该把第一次的翻译结果关闭了。这是正确的交互，你还有什么建议吗？

**Comment by Aberstin** [comment]
@maoruibin 为什么该项目源码里面缺少三个Java文件：DaggerServiceComponent、DaggerActivityComponent、DaggerAppComponent

**Comment by leizhiyuan** [comment]
@Aberstin  使用Dagger,是由Dagger生成这几个文件的.先build一下project就行了.

**Comment by Aberstin** [comment]
@leizhiyuan 好的，谢谢你的提醒！我去试一试
