### ISSUE TITLE
Hello 大佬

### ISSUE THREAD

**Issue by SMILEORIGIN** [maoruibin/TranslateApp#60]
我感觉我们做的app可以合并一下 哈哈，我的翻译app--易译，介绍地址：https://smileorigin.site/2017/10/21/Another/DynamicTranslate-Direction/

![](http://ojrfmxxyi.bkt.clouddn.com/2017年10月21日21_50_17_735.png)

**Comment by maoruibin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
不错，功能做的挺全面的，给个安装包体验一下呗，另外你完全可以把 APP 提交到应用商店，如果是考虑 api 使用次数，那你多虑了。



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2018年02月4日 13:42，smileorigin<notifications@github.com> 写道： 


我感觉我们做的app可以合并一下 哈哈，我的翻译app--易译，介绍地址：https://smileorigin.site/2017/10/21/Another/DynamicTranslate-Direction/

**Comment by SMILEORIGIN** [comment]
@maoruibin 主要这是去年5月完成的了，之后到现在堕落了没在做Android，现在想重新开始。给个邮箱，我发给你试试 哈哈
